"""
Structured geometry specifications.

``GeometrySpec`` is the validated, transport-agnostic description of a
suspension geometry: one spec model per suspension type, discriminated on the
``type`` field. The same models back YAML files (via ``kinematics.io``) and
structured API requests. Turn a spec into a live suspension with
:func:`kinematics.suspensions.build.build_suspension`.
"""

from __future__ import annotations

from typing import Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field, model_validator

from kinematics.core.enums import Units
from kinematics.core.point_ref import Side
from kinematics.schema.coercion import CIPointID, CISide, CIUnits, PydanticPoint3
from kinematics.schema.config import SuspensionConfig

# A named-point map: keys coerce case-insensitively to PointID, values to Point3.
HardpointMap = dict[CIPointID, PydanticPoint3]


class GeometrySpecBase(BaseModel):
    """Fields shared by every geometry spec."""

    model_config = ConfigDict(
        frozen=True,
        arbitrary_types_allowed=True,
        extra="forbid",
    )

    name: str = "unnamed"
    version: str = "0.0.0"
    units: CIUnits = Units.MILLIMETERS
    type: str
    config: SuspensionConfig


class DoubleWishboneGeometrySpec(GeometrySpecBase):
    """A single double-wishbone corner: a flat hardpoint map plus config."""

    type: Literal["double_wishbone"] = "double_wishbone"
    hardpoints: HardpointMap


class DoubleWishboneCoiloverGeometrySpec(GeometrySpecBase):
    """A double-wishbone corner with an outboard coilover."""

    type: Literal["double_wishbone_coilover"] = "double_wishbone_coilover"
    hardpoints: HardpointMap


class RockerSpringSpec(BaseModel):
    """The explicitly selected spring medium for a pushrod-rocker corner."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    type: Literal["torsion_bar", "coilover"]


class DoubleWishbonePushrodRockerGeometrySpec(GeometrySpecBase):
    """A double-wishbone corner with pushrod and rocker actuation."""

    type: Literal["double_wishbone_pushrod_rocker"] = "double_wishbone_pushrod_rocker"
    spring: RockerSpringSpec
    hardpoints: HardpointMap


class DoubleWishbonePushrodRockerArbGeometrySpec(GeometrySpecBase):
    """A pushrod-rocker corner with an anti-roll-bar droplink pickup."""

    type: Literal["double_wishbone_pushrod_rocker_arb"] = (
        "double_wishbone_pushrod_rocker_arb"
    )
    spring: RockerSpringSpec
    hardpoints: HardpointMap


class AxleHardpointsSpec(BaseModel):
    """
    Hardpoints block for an axle, in one of two modes.

    - **Mirror mode**: ``points`` describes one side (``side``, default left)
      and the other side is generated by reflecting through the XZ plane
      (``y -> -y``).
    - **Explicit mode**: ``left`` and ``right`` each give a full corner map.

    ``center`` holds shared, non-mirrored points (the ARB axis pair). Per-side
    maps may include ``DROPLINK_ARB``, the axle-only droplink ARB-end point.
    """

    model_config = ConfigDict(
        frozen=True,
        arbitrary_types_allowed=True,
        extra="forbid",
    )

    points: HardpointMap | None = None
    side: CISide = Side.LEFT
    mirror: bool = True
    left: HardpointMap | None = None
    right: HardpointMap | None = None
    center: HardpointMap = Field(default_factory=dict)

    @model_validator(mode="after")
    def check_mode(self) -> "AxleHardpointsSpec":
        explicit = self.left is not None or self.right is not None
        if explicit:
            if self.points is not None:
                raise ValueError(
                    "Give either a mirror-mode 'points' block or explicit "
                    "'left'/'right' blocks, not both."
                )
            if self.left is None or self.right is None:
                raise ValueError(
                    "Explicit-mode axle hardpoints require both 'left' and "
                    "'right' blocks."
                )
        else:
            if self.points is None:
                raise ValueError(
                    "Axle hardpoints require a mirror-mode 'points' block "
                    "or explicit 'left'/'right' blocks."
                )
            if not self.mirror:
                raise ValueError(
                    "Mirror-mode hardpoints with 'mirror: false' are ambiguous; "
                    "give both sides explicitly under 'left' and 'right'."
                )
            if self.side == Side.CENTER:
                raise ValueError("Mirror source side must be 'left' or 'right'.")
        return self

    @property
    def is_explicit(self) -> bool:
        """Whether both sides are given explicitly (vs. mirror mode)."""
        return self.left is not None


class DoubleWishboneAxleGeometrySpec(GeometrySpecBase):
    """A full axle: two double-wishbone corners plus shared center points."""

    type: Literal["double_wishbone_axle"] = "double_wishbone_axle"
    hardpoints: AxleHardpointsSpec


class DoubleWishbonePushrodRockerAxleGeometrySpec(GeometrySpecBase):
    """A full pushrod-rocker axle with a shared anti-roll bar."""

    type: Literal["double_wishbone_pushrod_rocker_axle"] = (
        "double_wishbone_pushrod_rocker_axle"
    )
    spring: RockerSpringSpec
    hardpoints: AxleHardpointsSpec


# Public common type for validated geometry specifications. Concrete dispatch
# is owned by kinematics.suspensions.registry, the single type catalogue.
GeometrySpec = GeometrySpecBase


def parse_geometry_spec(
    data: Mapping[str, Any],
) -> GeometrySpecBase:
    """
    Validate a raw mapping into the matching geometry spec.

    The ``type`` key selects the spec model (case-insensitive).

    Raises:
        ValueError: If ``type`` is missing/unknown or validation fails.
    """
    if "type" not in data:
        raise ValueError("Geometry type not specified")

    normalized = dict(data)
    type_key = str(normalized["type"]).lower()
    normalized["type"] = type_key
    try:
        # Deferred import avoids a module cycle: the registry definitions refer
        # back to the concrete schema classes declared above.
        from kinematics.suspensions.registry import get_suspension_definition

        definition = get_suspension_definition(type_key)
        if definition is None:
            raise ValueError(f"Unknown suspension type: {type_key}")
        return definition.spec_type.model_validate(normalized)
    except Exception as e:
        raise ValueError(f"Invalid geometry specification: {e}") from e
